In [47]:
from google.colab import drive
drive.mount("/content/drive",force_remount="TRUE")

Mounted at /content/drive


#Importing Dataset

In [48]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [49]:
tf.__version__

'2.4.0'

In [50]:
df=pd.read_csv("/content/drive/MyDrive/Machine Learning A-Z (Codes and Datasets)-20200808T101226Z-001/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv")
print(df)

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10

In [51]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [52]:
x=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


#Data Preprocessing

**LabelEncoding of "Gender" Column**

In [53]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [54]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

**OneHotEncoding of the "Geography" column**

In [55]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [56]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

**Splitting of the Training Set and the Test set**

In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

**Feature Scaling**

In [58]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test= sc.fit_transform(x_test)

#Creating the ANN model

**Initialization of the model**

In [59]:
ann = tf.keras.models.Sequential()

**Adding the first input layer**

In [60]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

Adding the Second input layer

In [61]:
ann.add(tf.keras.layers.Dense(units=36,activation="relu"))

**Adding the output layer**

In [62]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

*In case of nonbinary output we use the activation function of the output layer as "softmax".*

#Training the ANN model

**Compiling the model**

In [63]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics= ("accuracy"))

**Training the model**

In [64]:
ann.fit(x_train,y_train,batch_size=32,epochs=250)

Epoch 1/250
250/250 [==============================] - 1s 843us/step - loss: 0.5831 - accuracy: 0.7507
Epoch 2/250
250/250 [==============================] - 0s 859us/step - loss: 0.4450 - accuracy: 0.8091
Epoch 3/250
250/250 [==============================] - 0s 836us/step - loss: 0.4172 - accuracy: 0.8224
Epoch 4/250
250/250 [==============================] - 0s 803us/step - loss: 0.4011 - accuracy: 0.8310
Epoch 5/250
250/250 [==============================] - 0s 867us/step - loss: 0.3862 - accuracy: 0.8469
Epoch 6/250
250/250 [==============================] - 0s 859us/step - loss: 0.3711 - accuracy: 0.8504
Epoch 7/250
250/250 [==============================] - 0s 921us/step - loss: 0.3620 - accuracy: 0.8520
Epoch 8/250
250/250 [==============================] - 0s 846us/step - loss: 0.3546 - accuracy: 0.8585
Epoch 9/250
250/250 [==============================] - 0s 864us/step - loss: 0.3570 - accuracy: 0.8549
Epoch 10/250
250/250 [==============================] - 0s 848us/step - l

#Making predictions and evaluating the model

Homework

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?

In [65]:
P=ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
print(P)
print(P>0.5)

[[0.03230172]]
[[False]]


*The ANN model predict that the person will not leave te bank.*

Predicting the Test Set result

In [66]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1528   67]
 [ 203  202]]


0.865